name: Deploy to GitHub Pages

on:
  push:
    branches: [ "static" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install dependancy
        run: yarn install --immutable

      - name: Build webpack
        run: yarn build
        env:
          API_SERVER: api
          NO_AUDIO_MODE: "true"
          STATIC_MODE: "true"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
